# Generated by Django 2.1.7 on 2019-07-30 14:37

import django.db.models.manager
import djorm_pgfulltext.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='market/')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата цены')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('original_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='url')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('vendor_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Артикул')),
                ('available', models.BooleanField(verbose_name='Наличие')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последней синхронизации')),
                ('search_index', djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Market', verbose_name='Магазин')),
            ],
            managers=[
                ('search_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Rubric', verbose_name='Рубрика'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='base.Product', verbose_name='Продукт'),
        ),
    ]
