# Generated by Django 2.1.7 on 2019-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190730_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temporary_preparse_available',
            field=models.BooleanField(default=False, verbose_name='Наличие товара после парсинга'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Отображение товара на сайте'),
        ),
    ]
