# Generated by Django 2.2.4 on 2019-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190802_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(verbose_name='Дата последней синхронизации'),
        ),
    ]
